import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Footer from "@/Components/Footer";
import Navbar from "@/Components/NavBar";

import { AuthProvider } from "@/app/Context/AuthContext"; // ← AuthProvider import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-50 text-black max-w-7xl mx-auto`}
      >
     
        <AuthProvider>
          <Navbar />

          {children}

          <ToastContainer />

          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
